//
//  OnboardingComponents.swift
//  Ramble
//

import SwiftUI

// MARK: - Step state

enum OnboardingStep: Int, CaseIterable {
    case welcome
    case record
    case transcribe
    case send

    /// 1-based position in the 3-step body. Welcome returns nil (no dots shown).
    var progressIndex: Int? {
        switch self {
        case .welcome: return nil
        case .record: return 1
        case .transcribe: return 2
        case .send: return 3
        }
    }

    var previous: OnboardingStep? {
        switch self {
        case .welcome: return nil
        case .record: return .welcome
        case .transcribe: return .record
        case .send: return .transcribe
        }
    }

    static let bodyStepCount = 3
}

// MARK: - Design tokens

// `Color.brandRed` and `Color.brandRedSoft` are auto-generated by Xcode from
// the brand-red and brand-red-soft asset catalog entries — no manual extension
// needed. The shorter `ob*` aliases below mirror the onboarding-* assets so we
// don't have to spell out `Color.onboardingBg`/etc. everywhere.
extension Color {
    static let obBg = Color("onboarding-bg")
    static let obSurface = Color("onboarding-surface")
    static let obInk = Color("onboarding-ink")
    static let obInkSoft = Color("onboarding-ink-soft")
    static let obInkFaint = Color("onboarding-ink-faint")
    static let obHair = Color("onboarding-hair")
}

enum OnboardingFont {
    /// New York serif headline — used at 34pt for steps 2-4 and 48pt for the welcome screen.
    static func serifHeadline(size: CGFloat) -> Font {
        .system(size: size, design: .serif).weight(.medium)
    }

    static let body: Font = .system(size: 16)
    static let bodyLarge: Font = .system(size: 17)
    static let sectionHeader: Font = .system(size: 12, weight: .medium)
}

// MARK: - Page chrome

/// Scrollable body container for an onboarding step with an optional pinned
/// bottom bar (typically the primary CTA). The body fills the area above the
/// bottom bar; if its content overflows the body scrolls. The persistent nav
/// row lives in `OnboardingView` so it doesn't get re-mounted between steps.
struct OnboardingPage<Content: View, BottomBar: View>: View {
    @ViewBuilder let content: () -> Content
    @ViewBuilder let bottomBar: () -> BottomBar

    var body: some View {
        VStack(spacing: 0) {
            GeometryReader { geo in
                ScrollView {
                    VStack(spacing: 0) {
                        content()
                    }
                    .frame(maxWidth: .infinity)
                    .frame(minHeight: geo.size.height, alignment: .top)
                }
                .scrollBounceBehavior(.basedOnSize)
            }

            bottomBar()
        }
    }
}

extension OnboardingPage where BottomBar == EmptyView {
    init(@ViewBuilder content: @escaping () -> Content) {
        self.init(content: content, bottomBar: { EmptyView() })
    }
}

/// Persistent nav row: back chevron + segmented progress bar. Owned by
/// `OnboardingView` so the row stays mounted across step transitions and
/// only the active progress dot animates.
struct OnboardingNavRow: View {
    let activeStep: Int
    let onBack: () -> Void

    var body: some View {
        HStack(spacing: 0) {
            Button {
                HapticService.buttonTap()
                onBack()
            } label: {
                Image(systemName: "chevron.left")
                    .font(.system(size: 17, weight: .medium))
                    .foregroundStyle(Color.brandRed)
                    .frame(width: 44, height: 44)
                    .contentShape(Rectangle())
            }
            .buttonStyle(.plain)
            .accessibilityLabel("Back")

            Spacer()

            OnboardingProgressBar(activeStep: activeStep)

            Spacer()

            // Mirrors the back button width so the dots stay centered.
            Color.clear.frame(width: 44, height: 1)
        }
        .frame(height: 40)
        .padding(.horizontal, 16)
        .padding(.top, 16)
    }
}

// MARK: - Progress bar (segmented pill)

struct OnboardingProgressBar: View {
    /// 1-based: 1, 2, or 3.
    let activeStep: Int

    private let dotSize: CGFloat = 6
    private let activeWidth: CGFloat = 20
    private let spacing: CGFloat = 6

    var body: some View {
        HStack(spacing: spacing) {
            ForEach(1...OnboardingStep.bodyStepCount, id: \.self) { index in
                Capsule()
                    .fill(index <= activeStep ? Color.brandRed : Color.obHair)
                    .frame(width: index == activeStep ? activeWidth : dotSize, height: dotSize)
            }
        }
        .animation(.smooth(duration: 0.3), value: activeStep)
    }
}

// MARK: - Typographic primitives

/// Renders a serif headline. Pass a Text composition to mix italic accents:
///   `OnboardingHeadline(size: 34) { Text("First, ") + Text("let it hear you.").italic() }`
struct OnboardingHeadline: View {
    let size: CGFloat
    let alignment: TextAlignment
    let content: () -> Text

    init(size: CGFloat = 34, alignment: TextAlignment = .center, @ViewBuilder content: @escaping () -> Text) {
        self.size = size
        self.alignment = alignment
        self.content = content
    }

    var body: some View {
        content()
            .font(OnboardingFont.serifHeadline(size: size))
            .foregroundStyle(Color.obInk)
            .tracking(size >= 44 ? -1.0 : -0.6)
            .lineSpacing(0)
            .multilineTextAlignment(alignment)
            .fixedSize(horizontal: false, vertical: true)
    }
}

struct OnboardingBody: View {
    let text: String
    var maxWidth: CGFloat? = 320
    var alignment: TextAlignment = .center

    var body: some View {
        Text(text)
            .font(OnboardingFont.body)
            .foregroundStyle(Color.obInkSoft)
            .lineSpacing(2)
            .multilineTextAlignment(alignment)
            .frame(maxWidth: maxWidth)
    }
}

// MARK: - Wordmark (red dot + italic serif)

struct OnboardingWordmark: View {
    let size: CGFloat

    init(size: CGFloat = 48) {
        self.size = size
    }

    var body: some View {
        HStack(alignment: .center, spacing: size * 0.3) {
            Circle()
                .fill(Color.brandRed)
                .frame(width: size * 0.42, height: size * 0.42)

            Text("Ramble")
                .font(.system(size: size, design: .serif).italic())
                .fontWeight(.bold)
                .foregroundStyle(Color.obInk)
                .tracking(-0.5)
        }
    }
}

// MARK: - Illustration disc

/// 96pt soft-red disc for the step header illustration. The illustrations
/// already include the disc as part of the SVG, so this is just a sizer.
struct OnboardingIllustration: View {
    let name: String
    private let size: CGFloat = 96

    var body: some View {
        Image(name)
            .resizable()
            .scaledToFit()
            .frame(width: size, height: size)
            .accessibilityHidden(true)
    }
}

// MARK: - Brand surface card

/// Wraps content in the brand surface card — rounded `obSurface` fill.
/// Used to group rows in the onboarding flow. In Settings forms the equivalent
/// is `.listRowBackground(Color.obSurface)` on each row, which produces the
/// same visual but works inside Form's row chrome.
struct BrandCard<Content: View>: View {
    var cornerRadius: CGFloat = 12
    @ViewBuilder let content: () -> Content

    var body: some View {
        VStack(spacing: 0) {
            content()
        }
        .background(
            RoundedRectangle(cornerRadius: cornerRadius)
                .fill(Color.obSurface)
        )
    }
}

/// Hairline divider used between rows inside a `BrandCard`. Default leading
/// inset matches the icon column so the divider starts after the logo.
struct BrandRowDivider: View {
    var leadingInset: CGFloat = 50

    var body: some View {
        Rectangle()
            .fill(Color.obHair)
            .frame(height: 0.5)
            .padding(.leading, leadingInset)
    }
}

// MARK: - Send visual (voice → endpoint pill, animated dot)

/// Illustrated explainer showing a spoken thought traveling to a webhook URL.
/// Reused in onboarding and Settings to anchor the webhook concept.
struct SendVisual: View {
    var voiceText: String = "So I was thinking we should ship Tuesday morning."
    var endpointText: String = "my.api.com"

    private let cycleDuration: Double = 2.4

    var body: some View {
        HStack(spacing: 10) {
            voiceChip

            connector
                .frame(width: 56, height: 20)

            endpointChip
        }
        .padding(.vertical, 18)
        .padding(.horizontal, 16)
        .background(
            RoundedRectangle(cornerRadius: 14)
                .fill(Color.obSurface)
        )
    }

    private var voiceChip: some View {
        HStack(alignment: .center, spacing: 8) {
            Image(systemName: "waveform")
                .font(.system(size: 12))
                .foregroundStyle(Color.brandRed)

            Text(voiceText)
                .font(.system(size: 11, design: .serif).italic())
                .foregroundStyle(Color.obInkSoft)
                .lineLimit(2)
                .multilineTextAlignment(.leading)
                .frame(maxWidth: .infinity, minHeight: 30, alignment: .leading)
        }
        .padding(.vertical, 10)
        .padding(.horizontal, 12)
        .background(
            RoundedRectangle(cornerRadius: 12)
                .fill(Color.obBg)
                .overlay(
                    RoundedRectangle(cornerRadius: 12)
                        .stroke(Color.obHair, lineWidth: 0.5)
                )
        )
        .frame(maxWidth: .infinity, alignment: .leading)
    }

    private var connector: some View {
        TimelineView(.animation(minimumInterval: 1.0 / 60.0)) { context in
            let elapsed = context.date.timeIntervalSinceReferenceDate
            let progress = elapsed.truncatingRemainder(dividingBy: cycleDuration) / cycleDuration

            ZStack(alignment: .leading) {
                Rectangle()
                    .fill(Color.obHair)
                    .frame(height: 2)
                    .padding(.trailing, 6)

                Image(systemName: "chevron.right")
                    .font(.system(size: 10, weight: .semibold))
                    .foregroundStyle(Color.obInkFaint)
                    .frame(maxWidth: .infinity, alignment: .trailing)

                GeometryReader { geo in
                    let travel = max(0, geo.size.width - 14)
                    Circle()
                        .fill(Color.brandRed)
                        .frame(width: 9, height: 9)
                        .offset(
                            x: travel * CGFloat(progress),
                            y: (geo.size.height - 9) / 2
                        )
                        .opacity(travelOpacity(for: progress))
                }
            }
        }
    }

    private func travelOpacity(for progress: Double) -> Double {
        switch progress {
        case ..<0.15: return progress / 0.15
        case 0.85...: return max(0, (1 - progress) / 0.15)
        default: return 1
        }
    }

    private var endpointChip: some View {
        HStack(alignment: .center, spacing: 8) {
            Image(systemName: "paperplane.fill")
                .font(.system(size: 11))
                .foregroundStyle(Color.brandRed)

            Text(endpointText)
                .font(.system(size: 11, design: .monospaced))
                .foregroundStyle(Color.obInkSoft)
                .lineLimit(1)
                .truncationMode(.middle)
                .frame(maxWidth: .infinity, minHeight: 30, alignment: .leading)
        }
        .padding(.vertical, 10)
        .padding(.horizontal, 12)
        .background(
            RoundedRectangle(cornerRadius: 12)
                .fill(Color.obBg)
                .overlay(
                    RoundedRectangle(cornerRadius: 12)
                        .stroke(Color.obHair, lineWidth: 0.5)
                )
        )
        .frame(maxWidth: .infinity, alignment: .leading)
    }
}

// MARK: - Buttons

struct OnboardingPrimaryButton: View {
    let title: String
    let isDisabled: Bool
    let action: () -> Void

    init(title: String, isDisabled: Bool = false, action: @escaping () -> Void) {
        self.title = title
        self.isDisabled = isDisabled
        self.action = action
    }

    var body: some View {
        Button {
            HapticService.buttonTap()
            action()
        } label: {
            Text(title)
                .font(.system(size: 17, weight: .semibold))
                .foregroundStyle(.white)
                .frame(maxWidth: .infinity)
                .frame(height: 56)
                .background(
                    RoundedRectangle(cornerRadius: 14)
                        .fill(Color.brandRed)
                )
                .opacity(isDisabled ? 0.4 : 1)
        }
        .buttonStyle(.plain)
        .disabled(isDisabled)
    }
}

/// Full-width text button — surface fill, ink text, used as a "Maybe later" style action.
struct OnboardingSurfaceButton: View {
    let title: String
    let action: () -> Void

    var body: some View {
        Button {
            HapticService.buttonTap()
            action()
        } label: {
            Text(title)
                .font(.system(size: 17, weight: .medium))
                .foregroundStyle(Color.obInk)
                .frame(maxWidth: .infinity)
                .frame(height: 50)
                .background(
                    RoundedRectangle(cornerRadius: 12)
                        .fill(Color.obSurface)
                )
        }
        .buttonStyle(.plain)
    }
}

/// Centered red text link, full width.
struct OnboardingSecondaryLink: View {
    let title: String
    let action: () -> Void

    var body: some View {
        Button {
            HapticService.buttonTap()
            action()
        } label: {
            Text(title)
                .font(.system(size: 15))
                .foregroundStyle(Color.brandRed)
                .frame(maxWidth: .infinity)
                .padding(.vertical, 14)
        }
        .buttonStyle(.plain)
    }
}

// MARK: - Section header (uppercase tracked label)

struct OnboardingSectionHeader: View {
    let title: String
    var trailing: String? = nil

    var body: some View {
        HStack(alignment: .firstTextBaseline) {
            Text(title)
                .font(OnboardingFont.sectionHeader)
                .tracking(1.0)
                .textCase(.uppercase)
                .foregroundStyle(Color.obInkFaint)

            Spacer()

            if let trailing {
                Text(trailing)
                    .font(.system(size: 13))
                    .foregroundStyle(Color.obInkFaint)
            }
        }
        .padding(.horizontal, 16)
        .padding(.bottom, 6)
    }
}

// MARK: - Italic-red inline tag (e.g. "Required", "Recommended")

struct OnboardingItalicTag: View {
    let text: String

    var body: some View {
        Text(text)
            .font(.system(size: 13, design: .serif).italic().weight(.medium))
            .foregroundStyle(Color.brandRed)
    }
}

// MARK: - Appear-in animation

struct OnboardingAppearModifier: ViewModifier {
    let delay: Double
    @State private var visible = false

    func body(content: Content) -> some View {
        content
            .opacity(visible ? 1 : 0)
            .offset(y: visible ? 0 : 12)
            .onAppear {
                withAnimation(.easeOut(duration: 0.5).delay(delay)) {
                    visible = true
                }
            }
    }
}

extension View {
    func onboardingAppear(delay: Double = 0) -> some View {
        modifier(OnboardingAppearModifier(delay: delay))
    }
}
